---
- name: Add Apt Repository
  become: yes
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Install PHP
  become: yes
  apt: pkg=php7.0 state=latest

- name: install PHP packages
  become: yes
  apt: pkg="{{ item }}" state=latest
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-json
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-odbc
    - php7.0-pgsql
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xmlrpc
    - php7.0-opcache
    - php7.0-intl
    - php7.0-bz2
    - php7.0-xml