---
# handlers file for mysql
- name: start nginx
  service: name=nginx state=started
  become: yes

- name: stop nginx
  service: name=nginx state=stopped
  become: yes

- name: restart nginx
  become: yes
  service: name=nginx state=restarted