---
# handlers file for mysql
- name: start mysqld
  service: name=mysql state=started
  become: yes

- name: stop mysqld
  service: name=mysql state=stopped
  become: yes

- name: restart mysqld
  become: yes
  service: name=mysql state=restarted