---
# handlers file for mysql
- name: start mysqld
  service: name=mysqld state=started
  become: yes

- name: stop mysqld
  service: name=mysqld state=stopped
  become: yes

- name: restart mysqld
  become: yes
  service: name=mysqld state=restarted